import type { Activity, ActivityItem, Commitment, Reflection, UserProfile } from "./types";

const now = new Date("2026-04-30T19:30:00+02:00");
const isoDaysAgo = (days: number, hour: number, minute = 0) => {
  const date = new Date(now);
  date.setDate(now.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

export const demoUserId = "demo-user";

export const profile: UserProfile = {
  id: demoUserId,
  display_name: "Isa",
  avatar_url: null,
  bio_line: "Showing up for myself, every day.",
  reminder_time: "19:00",
  reminders_enabled: true,
  dark_mode: false,
  created_at: "2024-03-08T09:00:00.000Z",
};

export const activities: Activity[] = [
  {
    id: "gym",
    user_id: demoUserId,
    key: "gym",
    name: "Go to the gym",
    icon: "gym",
    icon_key: "dumbbell",
    color: "#6D3DF2",
    color_key: "blue",
    default_duration_min: 10,
    minimum_minutes: 10,
    benefits: ["Proud that you showed up", "Less stress, clearer mind", "More energy", "More confident", "Better mood"],
    is_default: true,
    is_archived: false,
    archived_at: null,
    sort_order: 1,
    created_at: "2024-03-08T09:00:00.000Z",
  },
  {
    id: "focus",
    user_id: demoUserId,
    key: "focus",
    name: "Do focused work",
    icon: "focus",
    icon_key: "laptop",
    color: "#22C55E",
    color_key: "green",
    default_duration_min: 10,
    minimum_minutes: 10,
    benefits: ["Clearer next step", "Less mental clutter", "More momentum", "Proud you began", "Calmer evening"],
    is_default: true,
    is_archived: false,
    archived_at: null,
    sort_order: 2,
    created_at: "2024-03-08T09:00:00.000Z",
  },
  {
    id: "outside",
    user_id: demoUserId,
    key: "outside",
    name: "Go outside",
    icon: "outside",
    icon_key: "footprints",
    color: "#F59E0B",
    color_key: "orange",
    default_duration_min: 10,
    minimum_minutes: 10,
    benefits: ["Fresh air helped", "Body feels awake", "Less stuck", "More grounded", "Better mood"],
    is_default: true,
    is_archived: false,
    archived_at: null,
    sort_order: 3,
    created_at: "2024-03-08T09:00:00.000Z",
  },
  {
    id: "social",
    user_id: demoUserId,
    key: "social",
    name: "Reach out to someone",
    icon: "social",
    icon_key: "message-circle",
    color: "#6D3DF2",
    color_key: "blue",
    default_duration_min: 5,
    minimum_minutes: 5,
    benefits: ["Less alone", "Connection feels good", "You were brave", "Warmer mood", "Future you remembers this"],
    is_default: true,
    is_archived: false,
    archived_at: null,
    sort_order: 4,
    created_at: "2024-03-08T09:00:00.000Z",
  },
  {
    id: "swimming",
    user_id: demoUserId,
    key: "custom",
    name: "Go swimming",
    icon: "custom",
    icon_key: "waves",
    color: "#38BDF8",
    color_key: "blue",
    default_duration_min: 10,
    minimum_minutes: 10,
    benefits: ["Refreshed after a swim", "Clearer mind", "Body feels awake", "Proud you went"],
    is_default: true,
    is_archived: false,
    archived_at: null,
    sort_order: 5,
    created_at: "2024-03-08T09:00:00.000Z",
  },
];

export const commitments: Commitment[] = [
  { id: "c1", user_id: demoUserId, activity_id: "gym", duration_minutes: 45, minimum_minutes: 10, started_at: isoDaysAgo(0, 19, 30), packing_started_at: isoDaysAgo(0, 19, 28), gone_at: isoDaysAgo(0, 19, 30), completed_at: isoDaysAgo(0, 20, 15), status: "completed" },
  { id: "c2", user_id: demoUserId, activity_id: "focus", duration_minutes: 60, minimum_minutes: 10, started_at: isoDaysAgo(0, 11), packing_started_at: isoDaysAgo(0, 10, 58), gone_at: isoDaysAgo(0, 11), completed_at: isoDaysAgo(0, 12), status: "completed" },
  { id: "c3", user_id: demoUserId, activity_id: "outside", duration_minutes: 30, minimum_minutes: 10, started_at: isoDaysAgo(1, 18), packing_started_at: isoDaysAgo(1, 17, 58), gone_at: isoDaysAgo(1, 18), completed_at: isoDaysAgo(1, 18, 30), status: "completed" },
  { id: "c4", user_id: demoUserId, activity_id: "focus", duration_minutes: 50, minimum_minutes: 10, started_at: isoDaysAgo(1, 10, 30), packing_started_at: isoDaysAgo(1, 10, 28), gone_at: isoDaysAgo(1, 10, 30), completed_at: isoDaysAgo(1, 11, 20), status: "completed" },
  { id: "c5", user_id: demoUserId, activity_id: "gym", duration_minutes: 40, minimum_minutes: 10, started_at: isoDaysAgo(2, 19, 15), packing_started_at: isoDaysAgo(2, 19, 13), gone_at: isoDaysAgo(2, 19, 15), completed_at: isoDaysAgo(2, 19, 55), status: "completed" },
  { id: "c6", user_id: demoUserId, activity_id: "gym", duration_minutes: 30, minimum_minutes: 10, started_at: isoDaysAgo(3, 18), packing_started_at: isoDaysAgo(3, 17, 58), gone_at: isoDaysAgo(3, 18), completed_at: isoDaysAgo(3, 18, 30), status: "completed" },
  { id: "c7", user_id: demoUserId, activity_id: "focus", duration_minutes: 30, minimum_minutes: 10, started_at: isoDaysAgo(4, 9), packing_started_at: isoDaysAgo(4, 8, 58), gone_at: isoDaysAgo(4, 9), completed_at: isoDaysAgo(4, 9, 30), status: "completed" },
  { id: "c8", user_id: demoUserId, activity_id: "social", duration_minutes: 15, minimum_minutes: 5, started_at: isoDaysAgo(6, 20), packing_started_at: isoDaysAgo(6, 19, 58), gone_at: isoDaysAgo(6, 20), completed_at: isoDaysAgo(6, 20, 15), status: "completed" },
  { id: "c9", user_id: demoUserId, activity_id: "outside", duration_minutes: 25, minimum_minutes: 10, started_at: isoDaysAgo(7, 17), packing_started_at: isoDaysAgo(7, 16, 58), gone_at: isoDaysAgo(7, 17), completed_at: isoDaysAgo(7, 17, 25), status: "completed" },
  { id: "c10", user_id: demoUserId, activity_id: "gym", duration_minutes: 35, minimum_minutes: 10, started_at: isoDaysAgo(8, 19), packing_started_at: isoDaysAgo(8, 18, 58), gone_at: isoDaysAgo(8, 19), completed_at: isoDaysAgo(8, 19, 35), status: "completed" },
  { id: "c11", user_id: demoUserId, activity_id: "focus", duration_minutes: 45, minimum_minutes: 10, started_at: isoDaysAgo(9, 14), packing_started_at: isoDaysAgo(9, 13, 58), gone_at: isoDaysAgo(9, 14), completed_at: isoDaysAgo(9, 14, 45), status: "completed" },
  { id: "c12", user_id: demoUserId, activity_id: "outside", duration_minutes: 20, minimum_minutes: 10, started_at: isoDaysAgo(10, 8), packing_started_at: isoDaysAgo(10, 7, 58), gone_at: isoDaysAgo(10, 8), completed_at: isoDaysAgo(10, 8, 20), status: "completed" },
];

export const reflections: Reflection[] = [
  { id: "r1", commitment_id: "c1", outcome: "better", feeling_score: 9, note: "Did not want to go, glad I did.", created_at: isoDaysAgo(0, 20, 16) },
  { id: "r2", commitment_id: "c2", outcome: "better", feeling_score: 8, note: null, created_at: isoDaysAgo(0, 12, 1) },
  { id: "r3", commitment_id: "c3", outcome: "same", feeling_score: 6, note: "Still a bit tired, but less stuck.", created_at: isoDaysAgo(1, 18, 31) },
  { id: "r4", commitment_id: "c4", outcome: "better", feeling_score: 8, note: null, created_at: isoDaysAgo(1, 11, 21) },
  { id: "r5", commitment_id: "c5", outcome: "better", feeling_score: 9, note: null, created_at: isoDaysAgo(2, 19, 56) },
  { id: "r6", commitment_id: "c6", outcome: "better", feeling_score: 8, note: null, created_at: isoDaysAgo(3, 18, 31) },
  { id: "r7", commitment_id: "c7", outcome: "worse", feeling_score: 4, note: "Pushed too late in the day.", created_at: isoDaysAgo(4, 9, 31) },
  { id: "r8", commitment_id: "c8", outcome: "better", feeling_score: 7, note: null, created_at: isoDaysAgo(6, 20, 16) },
  { id: "r9", commitment_id: "c9", outcome: "better", feeling_score: 8, note: null, created_at: isoDaysAgo(7, 17, 26) },
  { id: "r10", commitment_id: "c10", outcome: "better", feeling_score: 9, note: null, created_at: isoDaysAgo(8, 19, 36) },
  { id: "r11", commitment_id: "c11", outcome: "same", feeling_score: 6, note: null, created_at: isoDaysAgo(9, 14, 46) },
  { id: "r12", commitment_id: "c12", outcome: "better", feeling_score: 8, note: null, created_at: isoDaysAgo(10, 8, 21) },
];

const item = (activityId: string, sortOrder: number, label: string, iconKey: ActivityItem["icon_key"], priority: ActivityItem["priority"], hint: string | null = null): ActivityItem => ({
  id: `${activityId}-item-${sortOrder}`,
  user_id: demoUserId,
  activity_id: activityId,
  label,
  icon_key: iconKey,
  priority,
  hint,
  sort_order: sortOrder,
  is_door_step: false,
  created_at: "2024-03-08T09:00:00.000Z",
});

export const activityItems: ActivityItem[] = [
  item("gym", 1, "gym shoes", "footprints", "must", "by the door"),
  item("gym", 2, "water bottle", "droplet", "must", "filled up"),
  item("gym", 3, "keys + phone", "key", "must", "in your pocket"),
  item("gym", 4, "headphones", "headphones", "optional", "if helpful"),
  item("gym", 5, "towel", "shirt", "optional", "in your bag"),
  item("gym", 6, "snack", "shirt", "optional", "afterward"),
  item("outside", 1, "keys + phone", "key", "must", "in your pocket"),
  item("outside", 2, "weather layer", "shirt", "must", "for the air"),
  item("outside", 3, "headphones", "headphones", "optional", "if you want"),
  item("outside", 4, "sunglasses", "cloud-sun", "optional", "if bright"),
  item("outside", 5, "water", "droplet", "optional", "if longer"),
  item("social", 1, "pick the person", "user", "must"),
  item("social", 2, "type \"hey\"", "pencil", "must"),
  item("social", 3, "what to say", "message-circle", "optional", "one line"),
  item("social", 4, "pick a time", "send", "optional", "now or later"),
  item("focus", 1, "close tabs", "x-square", "must"),
  item("focus", 2, "water in reach", "droplet", "must"),
  item("focus", 3, "open the doc", "file-text", "must"),
  item("focus", 4, "phone away", "smartphone", "optional", "another room"),
  item("focus", 5, "headphones", "headphones", "optional"),
  item("focus", 6, "snack", "shirt", "optional", "nearby"),
  item("swimming", 1, "swimsuit", "shirt", "must", "in your bag"),
  item("swimming", 2, "towel", "shirt", "must", "for after swimming"),
  item("swimming", 3, "water bottle", "droplet", "must", "stay hydrated"),
  item("swimming", 4, "keys + phone", "key", "optional", "in your pocket"),
  item("swimming", 5, "headphones", "headphones", "optional", "if helpful"),
];
